# ---------- FLUTTER PACKAGE METADATA ----------
# ---------- FLUTTER PACKAGE NAME ----------
name: aban_demo_app

# ---------- SHORT DESCRIPTION ----------
description: "Overcoming Language Barriers in Khutbahs"

# ---------- PREVENT PUB DEV PUBLISHING ----------
publish_to: 'none'

# ---------- APP VERSION (major.minor.patch+build)----------
version: 1.0.0+1

# ---------- DART SDK CONSTRAINTS ----------
environment:
  sdk: ^3.11.0

# ---------- RUNTIME DEPENDENCIES ----------
dependencies:
  flutter:
    sdk: flutter

  # UTILITY PACKAGES
  http: ^1.1.0
  intl: ^0.18.1
  logger: ^2.0.1
  url_launcher: ^6.1.12
  flutter_native_splash: ^2.3.2

  # ICONS
  iconsax: ^0.0.8
  cupertino_icons: ^1.0.8

  # STATE MANAGEMENT
  get: ^4.6.5
  get_storage: ^2.1.1

# ---------- DEVELOPMENT and TESTING DEPENDENCIES ----------
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

# ---------- FLUTTER SPECIFIC SETTINGS ----------
flutter:
  uses-material-design: true

  # LOCAL ASSETS
  assets:
    - assets/logos/
    - assets/icons/
    - assets/images/

  # LOCAL FONTS
  fonts:
    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo-Regular.ttf
          weight: 400
        - asset: assets/fonts/Cairo-Medium.ttf
          weight: 500
        - asset: assets/fonts/Cairo-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Cairo-Bold.ttf
          weight: 700

    